### ISSUE TITLE
update github profile

### ISSUE THREAD

**Issue by thadkingcole** [thadkingcole/thadkingcole.github.io#5]
- [x] include the following:
  - [x] profile picture
  - [x] bio
  - [x] location
  - [x] email
  - [x] link to portfolio
- [x] pin desired project repos to profile
  - [x] make sure each project is deployed
  - [x] add a link to the deployed project in their README files
